---
## The global configuration for the argocd server
global:
  ## Options for the network policy
  networkPolicy:
    ## Enable the creation of the network policy
    create: true
    ## Deny all ingress traffic by default
    defaultDenyIngress: true

configs:
  ## Set the timeout for the reconciliation to 180 seconds
  timeout.reconciliation: 30s
  ## Specify the admin password for the argocd server
  secret:
    argocdServerAdminPassword: "$2a$10$fDcnV8BQs0kwlCpBnQaGgO8Pm7CLESJEU7DbXit/PIN1jOmlPU6JO"
    argocdServerAdminPasswordMtime: "2025-01-24T19:19:24GMT"
