## The name of the tenant cluster
cluster_name: dev
## The cloud vendor to use for the tenant cluster
cloud_vendor: kind
## The environment to use for the tenant cluster
environment: release
## The repository containing the tenant configuration
tenant_repository: https://github.com/appvia/kubernetes-platform.git
## The revision to use for the tenant repository
tenant_revision: main
## The path inside the tenant repository to use for the tenant cluster
tenant_path: release/standalone
## The cost center to use for the tenant cluster
tenant_cost_center: "123456"
## The repository containing the platform configuration
platform_repository: https://github.com/appvia/kubernetes-platform.git
## The revision to use for the platform repository
platform_revision: main
## The path to the kustomize overlay to use for the tenant cluster
platform_path: overlays/release
## The type of cluster we are (standalone, spoke or hub)
cluster_type: standalone
## The name of the tenant
tenant: test
## We use labels to enable/disable features in the tenant cluster
labels:
  # Enable the cost monitoring feature
  enable_kubecost: "true"
  # Enable the cert-manager feature
  enable_cert_manager: "true"
  # Enable the cilium CNI feature
  enable_cilium: "true"
  # Enable the external-secrets feature
  enable_external_secrets: "true"
  # Enable the karpenter nodepools features
  enable_karpenter_nodepools: "true"
  # Enable the kro feature
  enable_kro: "true"
  # Enable the kyverno feature
  enable_kyverno: "true"
## Annotations are using for additional metadata about the tenant cluster
annotations:
  platform.local/tenant: tenant
