
// Code generated by scripts/generate-template-fixtures.py; DO NOT EDIT.
// Regenerate: make generate-template-fixtures
// Merged-generator JSON fixtures live in template_patch_test.go.
package templates_test

const (
	patchSystemHelm = `{{- $context := toJson . | fromJson }}
spec:
  {{- if and .ignoreDifferences (gt (len .ignoreDifferences) 0) }}
  ignoreDifferences:
  {{- range $e := .ignoreDifferences }}
    - group: {{ default "" $e.group | quote }}
      kind: {{ $e.kind | quote }}
      {{- if $e.name }}
      name: {{ $e.name | quote }}
      {{- end }}
      {{- if $e.namespace }}
      namespace: {{ $e.namespace | quote }}
      {{- end }}
      {{- if $e.jsonPointers }}
      jsonPointers:
      {{- range $p := $e.jsonPointers }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.jqPathExpressions }}
      jqPathExpressions:
      {{- range $p := $e.jqPathExpressions }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.managedFieldsManagers }}
      managedFieldsManagers:
      {{- range $m := $e.managedFieldsManagers }}
        - {{ $m | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}

  sources:
    {{- if eq .repository "platform" }}
    - repoURL: "{{ .metadata.annotations.platform_repository }}"
      targetRevision: "{{ .metadata.annotations.platform_revision }}"
    {{- else }}
    - repoURL: "{{ .repository }}"
      targetRevision: "{{ .version }}"
      chart: '{{ default "" .chart }}'
    {{- end }}
      path: '{{ default "" .repository_path }}'
      helm:
        releaseName: "{{ normalize (default .feature .release_name) }}"
        ignoreMissingValueFiles: true
        valueFiles:
          - "$values/config/{{ .feature }}/all.yaml"
          - "$values/config/{{ .feature }}/{{ .metadata.labels.cloud_vendor }}.yaml"
          {{- if eq .metadata.annotations.tenant_path "." }}
          - "$tenant/config/{{ .feature }}/all.yaml"
          - "$tenant/config/{{ .feature }}/{{ .metadata.labels.cloud_vendor }}.yaml"
          - "$tenant/config/{{ .feature }}/{{ .metadata.labels.cluster_name }}.yaml"
          {{- else }}
          - "$tenant/{{ .metadata.annotations.tenant_path }}/config/{{ .feature }}/all.yaml"
          - "$tenant/{{ .metadata.annotations.tenant_path }}/config/{{ .feature }}/{{ .metadata.labels.cloud_vendor }}.yaml"
          - "$tenant/{{ .metadata.annotations.tenant_path }}/config/{{ .feature }}/{{ .metadata.labels.cluster_name }}.yaml"
          {{- end }}
        {{- if .values }}
        values: |
          {{ .values }}
        {{- end }}
        {{- if and (.parameters) (gt (len .parameters) 0) }}
        parameters:
        {{- range $param := .parameters }}
          - name: {{ $param.name }}
        {{- if not (hasPrefix "." $param.value) }}
            value: "{{ $param.value }}"
        {{- else }}
        {{- $params := splitList "." (trimPrefix "." $param.value) }}
        {{- $value := default $param.default "" }}
            {{- if eq (len $params) 1 }}
            {{- $value = dig (index $params 0) "" $context }}
            {{- else if eq (len $params) 2 }}
            {{- $value = dig (index $params 0) (index $params 1) "" $context }}
            {{- else if eq (len $params) 3 }}
            {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
            {{- else if eq (len $params) 4 }}
            {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
            {{- end }}
            value: {{ default $param.default $value }}
        {{- end }}
        {{- end }}
        {{- end }}

    - repoURL: "{{ .metadata.annotations.platform_repository }}"
      targetRevision: "{{ .metadata.annotations.platform_revision }}"
      ref: values

    - repoURL: "{{ .metadata.annotations.tenant_repository }}"
      targetRevision: "{{ .metadata.annotations.tenant_revision }}"
      ref: tenant`

	patchSystemKustomize = `{{- $context := toJson . | fromJson }}
spec:
  {{- if and .ignoreDifferences (gt (len .ignoreDifferences) 0) }}
  ignoreDifferences:
  {{- range $e := .ignoreDifferences }}
    - group: {{ default "" $e.group | quote }}
      kind: {{ $e.kind | quote }}
      {{- if $e.name }}
      name: {{ $e.name | quote }}
      {{- end }}
      {{- if $e.namespace }}
      namespace: {{ $e.namespace | quote }}
      {{- end }}
      {{- if $e.jsonPointers }}
      jsonPointers:
      {{- range $p := $e.jsonPointers }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.jqPathExpressions }}
      jqPathExpressions:
      {{- range $p := $e.jqPathExpressions }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.managedFieldsManagers }}
      managedFieldsManagers:
      {{- range $m := $e.managedFieldsManagers }}
        - {{ $m | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
  source:
    ## If a kustomize.repository we don't use the .path.path
    {{- if .kustomize.repository }}
    path: "{{ .kustomize.path }}"
    {{- end }}

    kustomize:
      commonLabels:
        {{- range $k, $v := .kustomize.commonLabels }}
        {{ $k }}: {{ $v }}
        {{- end }}
      commonAnnotations:
        {{- range $k, $v := .kustomize.commonAnnotations }}
        {{ $k }}: {{ $v }}
        {{- end }}
      {{- if and .kustomize.patches (gt (len .kustomize.patches) 0) }}
      ## Save the context for the dig function
      patches:
        {{- range $change := .kustomize.patches }}
        - target:
            kind: {{ $change.target.kind }}
            name: {{ $change.target.name }}
          patch: |
            {{- range $patch := $change.patch }}
            {{- $value := default $patch.default "" }}
              - op: {{ $patch.op }}
                path: {{ $patch.path }}
                {{- if not (hasPrefix "." $patch.key) }}
                {{- $value = printf "%s%s" $patch.prefix $value }}
                value: "{{ default $patch.default $value }}"
                {{- else }}
                {{- $params := splitList "." (trimPrefix "." $patch.key) }}
                {{- if eq (len $params) 1 }}
                {{- $value = dig (index $params 0) "" $context }}
                {{- else if eq (len $params) 2 }}
                {{- $value = dig (index $params 0) (index $params 1) "" $context }}
                {{- else if eq (len $params) 3 }}
                {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
                {{- else if eq (len $params) 4 }}
                {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
                {{- end }}
                {{- if $patch.prefix }}
                {{- $value = printf "%s%s" $patch.prefix $value }}
                {{- end }}
                value: {{ default $patch.default $value }}
                {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}`

	patchTenantAppsHelm = `## If the path is a applications path, we need to get the namespace from the path
{{- $index := 0 }}
{{- range $i, $k := .path.segments }}
{{- if (eq "applications" $k) }}
{{- $index = $i }}
{{- break }}
{{- end }}
{{- end }}
{{- $context := toJson . | fromJson }}
{{- $namespace := index .path.segments (add1 $index) }}
spec:
  {{- if and .ignoreDifferences (gt (len .ignoreDifferences) 0) }}
  ignoreDifferences:
  {{- range $e := .ignoreDifferences }}
    - group: {{ default "" $e.group | quote }}
      kind: {{ $e.kind | quote }}
      {{- if $e.name }}
      name: {{ $e.name | quote }}
      {{- end }}
      {{- if $e.namespace }}
      namespace: {{ $e.namespace | quote }}
      {{- end }}
      {{- if $e.jsonPointers }}
      jsonPointers:
      {{- range $p := $e.jsonPointers }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.jqPathExpressions }}
      jqPathExpressions:
      {{- range $p := $e.jqPathExpressions }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.managedFieldsManagers }}
      managedFieldsManagers:
      {{- range $m := $e.managedFieldsManagers }}
        - {{ $m | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}

  destination:
    namespace: {{ $namespace }}
    server: "{{ .server }}"

  sources:
    ## The kustomize folder includes the default settings and manifests
    ## for all namespace creations for the tenant applications - i.e.
    ## service accounts, network policies, etc.
    - repoURL: "{{ .metadata.annotations.platform_repository }}"
      targetRevision: "{{ .metadata.annotations.platform_revision }}"
      path: "apps/tenant/namespace"
      kustomize:
        patches:
          - target:
              kind: Namespace
              labelSelector: "platform.local/namespace=tenant"
            patch: |
              - op: replace
                path: /metadata/name
                value: "{{ $namespace }}"

    - repoURL: "{{ .helm.repository }}"
      {{- if .helm.version }}
      targetRevision: "{{ .helm.version }}"
      {{- end }}
      {{- if .helm.chart }}
      chart: "{{ .helm.chart }}"
      {{- end }}
      path: "{{ .helm.path }}"
      helm:
        releaseName: "{{ default .path.basenameNormalized .helm.release_name }}"
        ignoreMissingValueFiles: true
        valueFiles:
          - "$values/{{ .path.path }}/values/all.yaml"
          - "$values/{{ .path.path }}/values/{{ .metadata.annotations.tenant }}.yaml"
          - "$values/{{ .path.path }}/values/{{ .metadata.labels.environment }}.yaml"
          - "$values/{{ .path.path }}/values/{{ .metadata.labels.cluster_name }}.yaml"
        {{- if .helm.values }}
        values: |
          {{- .helm.values | nindent 14 }}
        {{- end }}
        {{- if and (.helm.parameters) (gt (len .helm.parameters) 0) }}
        parameters:
        {{- range $param := .helm.parameters }}
          - name: {{ $param.name }}
        {{- if not (hasPrefix "." $param.value) }}
            value: "{{ $param.value }}"
        {{- else }}
        {{- $params := splitList "." (trimPrefix "." $param.value) }}
        {{- $value := default $param.default "" }}
            {{- if eq (len $params) 1 }}
            {{- $value = dig (index $params 0) "" $context }}
            {{- else if eq (len $params) 2 }}
            {{- $value = dig (index $params 0) (index $params 1) "" $context }}
            {{- else if eq (len $params) 3 }}
            {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
            {{- else if eq (len $params) 4 }}
            {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
            {{- end }}
            value: {{ default $param.default $value }}
        {{- end }}
        {{- end }}
        {{- end }}

    # Source the platform values
    - repoURL: "{{ .metadata.annotations.tenant_repository }}"
      targetRevision: "{{ .metadata.annotations.tenant_revision }}"
      ref: values`

	patchTenantAppsKustomize = `{{- $index := 0 }}
{{- range $i, $k := .path.segments }}
{{- if (eq "applications" $k) }}
{{- $index = $i }}
{{- break }}
{{- end }}
{{- end }}
{{- $namespace := index .path.segments (add1 $index) }}
{{- $context := toJson . | fromJson }}
spec:
  {{- if and .ignoreDifferences (gt (len .ignoreDifferences) 0) }}
  ignoreDifferences:
  {{- range $e := .ignoreDifferences }}
    - group: {{ default "" $e.group | quote }}
      kind: {{ $e.kind | quote }}
      {{- if $e.name }}
      name: {{ $e.name | quote }}
      {{- end }}
      {{- if $e.namespace }}
      namespace: {{ $e.namespace | quote }}
      {{- end }}
      {{- if $e.jsonPointers }}
      jsonPointers:
      {{- range $p := $e.jsonPointers }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.jqPathExpressions }}
      jqPathExpressions:
      {{- range $p := $e.jqPathExpressions }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.managedFieldsManagers }}
      managedFieldsManagers:
      {{- range $m := $e.managedFieldsManagers }}
        - {{ $m | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}

  destination:
    namespace: "{{ $namespace }}"
    server: "{{ .server }}"

  sources:
    - repoURL: "{{ .metadata.annotations.platform_repository }}"
      targetRevision: "{{ .metadata.annotations.platform_revision }}"
      path: "apps/tenant/namespace"
      kustomize:
        commonLabels:
          {{- range $k, $v := .kustomize.commonLabels }}
          {{ $k }}: {{ $v }}
          {{- end }}
        commonAnnotations:
          {{- range $k, $v := .kustomize.commonAnnotations }}
          {{ $k }}: {{ $v }}
          {{- end }}
        patches:
          - target:
              kind: Namespace
              labelSelector: "platform.local/namespace=tenant"
            patch: |
              - op: replace
                path: /metadata/name
                value: "{{ $namespace }}"

    ## We either use the tenant repository of the kustomize.repository
    - repoURL: "{{ default .metadata.annotations.tenant_repository .kustomize.repository }}"
      ## We either use the tenant revision of the kustomize.revision (external revision)
      targetRevision: "{{ default .metadata.annotations.tenant_revision .kustomize.revision }}"
      ## We either use the tenant path of the kustomize.path (external path)
      {{- if .kustomize.repository }}
      path: "{{ .kustomize.path }}"
      {{- else }}
      path: "{{ printf "%s/%s" .path.path .kustomize.path }}"
      {{- end }}

      kustomize:
        {{- if and (.kustomize.patches) (gt (len .kustomize.patches) 0) }}
        patches:
          ## Save the context for the dig function
          {{- range $change := .kustomize.patches }}
          - target:
              kind: {{ $change.target.kind }}
              name: {{ $change.target.name }}
            patch: |
            {{- range $patch := $change.patch }}
            {{- $value := default $patch.default "" }}
              - op: {{ $patch.op }}
                path: {{ $patch.path }}
                {{- if not (hasPrefix "." $patch.key) }}
                {{- $value = printf "%s%s" $patch.prefix $value }}
                value: "{{ default $patch.default $value }}"
                {{- else }}
                {{- $params := splitList "." (trimPrefix "." $patch.key) }}
                {{- if eq (len $params) 1 }}
                {{- $value = dig (index $params 0) "" $context }}
                {{- else if eq (len $params) 2 }}
                {{- $value = dig (index $params 0) (index $params 1) "" $context }}
                {{- else if eq (len $params) 3 }}
                {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
                {{- else if eq (len $params) 4 }}
                {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
                {{- end }}
                {{- if $patch.prefix }}
                {{- $value = printf "%s%s" $patch.prefix $value }}
                {{- end }}
                value: {{ default $patch.default $value }}
                {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}`

	patchTenantSystemHelm = `{{- $create_namespace := default true .namespace.create }}
{{- $namespace := .namespace.name }}
{{- $context := toJson . | fromJson }}
spec:
  {{- if and .ignoreDifferences (gt (len .ignoreDifferences) 0) }}
  ignoreDifferences:
  {{- range $e := .ignoreDifferences }}
    - group: {{ default "" $e.group | quote }}
      kind: {{ $e.kind | quote }}
      {{- if $e.name }}
      name: {{ $e.name | quote }}
      {{- end }}
      {{- if $e.namespace }}
      namespace: {{ $e.namespace | quote }}
      {{- end }}
      {{- if $e.jsonPointers }}
      jsonPointers:
      {{- range $p := $e.jsonPointers }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.jqPathExpressions }}
      jqPathExpressions:
      {{- range $p := $e.jqPathExpressions }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.managedFieldsManagers }}
      managedFieldsManagers:
      {{- range $m := $e.managedFieldsManagers }}
        - {{ $m | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}

  destination:
    namespace: {{ $namespace }}
    server: "{{ .server }}"

  sources:
    {{- if $create_namespace }}
    ## The kustomize folder includes the default settings and manifests
    ## for all namespace creations for the tenant applications - i.e.
    ## service accounts, network policies, etc.
    - repoURL: "{{ .metadata.annotations.platform_repository }}"
      targetRevision: "{{ .metadata.annotations.platform_revision }}"
      path: "apps/tenant/namespace"
      kustomize:
        patches:
          - target:
              kind: Namespace
              labelSelector: "platform.local/namespace=tenant"
            patch: |
              - op: replace
                path: /metadata/name
                value: "{{ $namespace }}"
              - op: replace
                path: /metadata/labels/platform.local~1namespace-type
                value: "tenant-system"
    {{- end }}

    - repoURL: "{{ .helm.repository }}"
      {{- if .helm.version }}
      targetRevision: "{{ .helm.version }}"
      {{- end }}
      {{- if .helm.chart }}
      chart: "{{ .helm.chart }}"
      {{- end }}
      path: "{{ .helm.path }}"
      helm:
        releaseName: "{{ default .path.basenameNormalized .helm.release_name }}"
        ignoreMissingValueFiles: true
        valueFiles:
          - "$values/{{ .path.path }}/values/all.yaml"
          - "$values/{{ .path.path }}/values/{{ .metadata.annotations.tenant }}.yaml"
          - "$values/{{ .path.path }}/values/{{ .metadata.labels.environment }}.yaml"
          - "$values/{{ .path.path }}/values/{{ .metadata.labels.cluster_name }}.yaml"
        {{- if and (.helm.parameters) (gt (len .helm.parameters) 0) }}
        parameters:
        {{- range $param := .helm.parameters }}
          - name: {{ $param.name }}
        {{- if not (hasPrefix "." $param.value) }}
            value: "{{ $param.value }}"
        {{- else }}
        {{- $params := splitList "." (trimPrefix "." $param.value) }}
        {{- $value := default $param.default "" }}
            {{- if eq (len $params) 1 }}
            {{- $value = dig (index $params 0) "" $context }}
            {{- else if eq (len $params) 2 }}
            {{- $value = dig (index $params 0) (index $params 1) "" $context }}
            {{- else if eq (len $params) 3 }}
            {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
            {{- else if eq (len $params) 4 }}
            {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
            {{- end }}
            value: {{ default $param.default $value }}
        {{- end }}
        {{- end }}
        {{- end }}

    # Source the platform values
    - repoURL: "{{ .metadata.annotations.tenant_repository }}"
      targetRevision: "{{ .metadata.annotations.tenant_revision }}"
      ref: values`

	patchTenantSystemKustomize = `{{- $create_namespace := default true .namespace.create }}
{{- $namespace := .namespace.name }}
{{- $context := toJson . | fromJson }}
spec:
  {{- if and .ignoreDifferences (gt (len .ignoreDifferences) 0) }}
  ignoreDifferences:
  {{- range $e := .ignoreDifferences }}
    - group: {{ default "" $e.group | quote }}
      kind: {{ $e.kind | quote }}
      {{- if $e.name }}
      name: {{ $e.name | quote }}
      {{- end }}
      {{- if $e.namespace }}
      namespace: {{ $e.namespace | quote }}
      {{- end }}
      {{- if $e.jsonPointers }}
      jsonPointers:
      {{- range $p := $e.jsonPointers }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.jqPathExpressions }}
      jqPathExpressions:
      {{- range $p := $e.jqPathExpressions }}
        - {{ $p | quote }}
      {{- end }}
      {{- end }}
      {{- if $e.managedFieldsManagers }}
      managedFieldsManagers:
      {{- range $m := $e.managedFieldsManagers }}
        - {{ $m | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}

  destination:
    namespace: {{ $namespace }}
    server: "{{ .server }}"

  sources:
    # We don't create the namespace if the user has explicity set the
    # .namespace.create = false - else defaults to true
    {{- if $create_namespace }}
    - repoURL: "{{ .metadata.annotations.platform_repository }}"
      targetRevision: "{{ .metadata.annotations.platform_revision }}"
      path: "apps/tenant/namespace"
      kustomize:
        commonLabels:
          {{- range $k, $v := .kustomize.commonLabels }}
          {{ $k }}: {{ $v }}
          {{- end }}
        commonAnnotations:
          {{- range $k, $v := .kustomize.commonAnnotations }}
          {{ $k }}: {{ $v }}
          {{- end }}
        patches:
          - target:
              kind: Namespace
              labelSelector: "platform.local/namespace=tenant"
            patch: |
              - op: replace
                path: /metadata/name
                value: "{{ $namespace }}"
    {{- end }}

    ## We either use the tenant repository of the kustomize.repository
    - repoURL: "{{ default .metadata.annotations.tenant_repository .kustomize.repository }}"
      ## We either use the tenant revision of the kustomize.revision (external revision)
      targetRevision: "{{ default .metadata.annotations.tenant_revision .kustomize.revision }}"
      ## We either use the tenant path of the kustomize.path (external path)
      {{- if .kustomize.repository }}
      path: "{{ .kustomize.path }}"
      {{- else }}
      path: "{{ printf "%s/%s" .path.path .kustomize.path }}"
      {{- end }}

      kustomize:
        {{- if and (.kustomize.patches) (gt (len .kustomize.patches) 0) }}
        patches:
          ## Save the context for the dig function
          {{- range $change := .kustomize.patches }}
          - target:
              kind: {{ $change.target.kind }}
              name: {{ $change.target.name }}
            patch: |
            {{- range $patch := $change.patch }}
            {{- $value := default $patch.default "" }}
              - op: {{ $patch.op }}
                path: {{ $patch.path }}
                {{- if not (hasPrefix "." $patch.key) }}
                {{- $value = printf "%s%s" $patch.prefix $value }}
                value: "{{ default $patch.default $value }}"
                {{- else }}
                {{- $params := splitList "." (trimPrefix "." $patch.key) }}
                {{- if eq (len $params) 1 }}
                {{- $value = dig (index $params 0) "" $context }}
                {{- else if eq (len $params) 2 }}
                {{- $value = dig (index $params 0) (index $params 1) "" $context }}
                {{- else if eq (len $params) 3 }}
                {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
                {{- else if eq (len $params) 4 }}
                {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
                {{- end }}
                {{- if $patch.prefix }}
                {{- $value = printf "%s%s" $patch.prefix $value }}
                {{- end }}
                value: {{ default $patch.default $value }}
                {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}`

)
