---
opencost:
  # Main exporter configuration
  exporter:
    # Additional configuration
    extraEnv:
      # API port for OpenCost
      API_PORT: "9003"
      # AWS Configuration
      AWS_REGION: PATCH_ME
      # Use regional STS endpoints for better performance
      AWS_STS_REGIONAL_ENDPOINTS: "regional"
      # Token file for IAM authentication
      AWS_WEB_IDENTITY_TOKEN_FILE: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
      # Enable EKS-specific pricing
      AWS_EKS_PRICING_ENABLED: "true"
      # Disable Athena for simplicity
      AWS_ATHENA_ENABLED: "false"
      # CloudWatch Export - send metrics to CloudWatch
      AWS_CLOUDWATCH_METRICS_ENABLED: "true"
      # Namespace for CloudWatch metrics
      AWS_CLOUDWATCH_METRICS_NAMESPACE: "OpenCost/EKS"

  # Volume mounts for storage and IAM tokens
  extraVolumeMounts:
    - name: aws-iam-token
      mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      readOnly: true

  extraVolumes:
    - name: aws-iam-token
      # The projected for the extra volume for aws-iam-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
