---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.local/type: tenant
spec:
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: namespace-admin
  subjects:
    - kind: ServiceAccount
      name: namespace-admin
