---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - network-policies.yaml
  - roles.yaml
  - bindings.yaml
