---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  labels:
    platform.local/type: tenant
    app.kubernetes.io/managed-by: argocd
spec:
  rules:
    - apiGroups:
        - "*"
      resources:
        - "*"
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
