---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-amd64
  labels:
    karpenter.sh/nodepool: default-amd64
    karpenter.sh/nodepool-class: default
  annotations:
    karpenter.sh/nodepool-version: "1.2.1"
    karpenter.sh/nodepool-provider: aws
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand", "reserved"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
  ## The weight for the node pool
  weight: 100
  ## Limits for the node pool
  limits:
    cpu: 1000
  ## The disruption settings for the node pool
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-graviton
  labels:
    karpenter.sh/nodepool: default-graviton
    karpenter.sh/nodepool-class: default
  annotations:
    karpenter.sh/nodepool-version: "1.2.1"
    karpenter.sh/nodepool-provider: aws
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand", "reserved"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
  ## The weight for the node pool
  weight: 50
  ## Limits for the node pool
  limits:
    cpu: 1000
  ## The disruption settings for the node pool
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
