---
apiVersion: karpenter.sh/v1alpha5
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  # Optional, configures IMDS for the instance
  associatePublicIpAddress: false
  ## The AMI family to use for the node class
  amiFamily: Bottlerocket
  ## The AMI selector to use for the node class
  amiSelectorTerms:
    - alias: bottlerocket@latest
  ## The subnet selector to use for the node class - filled in by the kustomize patch
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: CLUSTER_NAME
  ## The security group selector to use for the node class - filled in by the kustomize patch
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: CLUSTER_NAME
  ## Detailed monitoring to enable for the node class
  detailedMonitoring: false
  ## AWS Tags to apply to the node class
  tags:
    CostCenter: "unknown"
    Environment: "unknown"
    Product: "unknown"
  ## The metadata options to use for the node class
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required

  ## The block device mappings to use for the node class
  blockDeviceMappings:
    - deviceName: "/dev/xvda"
      ebs:
        volumeSize: 2Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
    - deviceName: "/dev/xvda"
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
