---
##
## This application set is used to create Applications for each of the
## platform kustomize charts, defined in the ./platform directory.
##
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-kustomize
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true

  ## Add a strategy permiting us to control the ordering of resources
  ## by using labelling.
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  ## Generate applications from the platform repository
  generators:
    - matrix:
        generators:
          - git:
              repoURL: PLATFORM_REPO
              revision: PLATFORM_REPO_REVISION
              files:
                - path: "platform/{{ .cloud_vendor }}/**/kustomize.yaml"
                - path: "platform/oss/**/kustomize.yaml"
            selector:
              matchExpressions:
                - key: kustomize.path
                  operator: Exists
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
                  - key: "{{ .kustomize.feature }}"
                    operator: In
                    values: ["true"]

  ## Sync Policy for the ApplicationSet
  syncPolicy:
    # Prevents ApplicationSet controller from modifying Applications. Delete is allowed.
    applicationsSync: create-delete

  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "system-kustomize-{{ .path.basenameNormalized }}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd
        app.kubernetes.io/managed-by: platform
        app.kubernetes.io/instance: platform
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/type: kustomize
        phase: primary

    spec:
      ## The project to use for the application
      project: system

      ## The sources to use for the application
      source:
        repoURL: "{{ .metadata.annotations.platform_repository }}"
        targetRevision: "{{ .metadata.annotations.platform_revision }}"
        path: '{{ printf "%s/%s" .path.path .kustomize.path }}'
        kustomize: {}

      ## Destination is the cluster to deploy to
      destination:
        server: https://kubernetes.default.svc
        ## /applications/TYPE/[2]/FILE.yaml or .helm.namespace
        namespace: "{{ default (index .path.segments 2) .kustomize.namespace }}"

      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          backoff:
            duration: 60s
            maxDuration: 2m
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
