---
apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: aws
  namespace: terraform-system
  labels:
    app.kubernetes.io/component: provider
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: aws
    app.kubernetes.io/part-of: terranetes
spec:
  ## Source of the credentials for the provider
  source: injected
  ## The provider to use
  provider: aws
  ## Preload options for the provider
  preload:
    # Indicates if the preloading should be enabled
    enabled: true
    # Is the EKS cluster we use to pivot network and settings around
    cluster: CLUSTER_NAME
    # Is the cloud region the cluster above resides
    region: CLUSTER_REGION
    # Is the terranetes context resource we should provision
    context: default
