---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: argocd
  platform.local/type: standalone

resources:
  - platform.yaml
  - ../../apps/argocd
