---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-no-traffic-distribution
  annotations:
    policies.kyverno.io/title: Deny Services without trafficDistribution
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      When Kubernetes version is >= 1.34, all Services must have a
      .spec.trafficDistribution field set to either PreferSameZone or PreferSameNode.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-traffic-distribution
      match:
        any:
          - resources:
              kinds:
                - Service
      preconditions:
        any:
          - key: "{{ clusterInfo.kubernetesVersion }}"
            operator: GreaterThanOrEquals
            value: "1.34"
      validate:
        message: "Service must have .spec.trafficDistribution set to either PreferSameZone or PreferSameNode when Kubernetes version >= 1.34"
        pattern:
          spec:
            trafficDistribution: "PreferSameZone | PreferSameNode"
