{{- if and .Values.externalSecret.enabled .Values.externalSecret.secretName (ne .Values.externalSecret.secretName "") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.externalSecret.namespace }}
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # RefreshInterval is the amount of time before the values reading
  # again. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m",
  # "h" (from time.ParseDuration)
  refreshInterval: 1h

  # Optional, SecretStoreRef defines the default SecretStore to use
  # when fetching the secret data.
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore

  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:
    # The secret name of the resource
    name: {{ .Values.secretName }}

    # Specify a blueprint for the resulting Kind=Secret
    template:
      # Labels and annotations to set on the Secret.
      metadata:
        labels:
          app.kubernetes.io/name: argocd-notifications
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/managed-by: {{ .Release.Service }}
      data:
        slack-token: "{{ `{{ .slackToken }}` }}"

  # Data defines the connection between the Kubernetes Secret keys
  # and the Provider data
  data:
    - secretKey: slackToken
      remoteRef:
        # The name of the secret inside aws secrets manager
        key: {{ .Values.externalSecret.secretName }}
        # The property inside the secret that contains the token
        property: {{ .Values.externalSecret.key }}
        # Setting the conversion strategy to default
        conversionStrategy: Default
        # Addig the decoding strategy to none to avoid base64
        # decoding of the secret value
        decodingStrategy: None
        # Adding a metadata policy to add the label
        # "managed-by: argocd-notifications" to the secret
        metadataPolicy: None
{{- end }}
