{{- if and .Values.externalSecret.secretName (ne .Values.externalSecret.secretName "") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.externalSecret.namespace }}
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.clusterSecretsStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    template:
      data:
        slack-token: "{{ `{{ .slackToken }}` }}"
  data:
    - secretKey: slackToken
      remoteRef:
        # The name of the secret inside aws secrets manager
        key: {{ .Values.externalSecret.secretName }}
        # The property inside the secret that contains the token
        property: {{ .Values.externalSecret.key }}
{{- end }}
