{{- if and .Values.externalSecret.secretName (ne .Values.externalSecret.secretName "") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.externalSecret.namespace }}
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    template:
      engineVersion: v2
      data:
        slack-token: "{{ `{{ .slackToken }}` }}"
  data:
    - secretKey: slackToken
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
{{- end }}
