{{- if and (not .Values.externalSecret.enabled) .Values.directSecret.slackToken (ne .Values.directSecret.slackToken "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  slack-token: {{ .Values.directSecret.slackToken | b64enc }}
{{- end }}
