#!/usr/bin/env python3
"""
Regenerate tests/templates/embedded_fixtures_test.go (embedded templatePatch
bodies only).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# The root of the repository, and the output file to write. The input files are
ROOT = Path(__file__).resolve().parent.parent
# The output file is a Go source file, so we can embed the templatePatch bodies
OUT = ROOT / "tests/templates/fixtures_test.go"

# List of files to extract .spec.templatePatch from, and the constant name to
# assign it to.
APPSETS = [
    ("patchSystemHelm", "apps/system/system-helm.yaml"),
    ("patchSystemKustomize", "apps/system/system-kustomize.yaml"),
    ("patchTenantAppsHelm", "apps/tenant/apps-helm.yaml"),
    ("patchTenantAppsKustomize", "apps/tenant/apps-kustomize.yaml"),
    ("patchTenantSystemHelm", "apps/tenant/system-helm.yaml"),
    ("patchTenantSystemKustomize", "apps/tenant/system-kustomize.yaml"),
]

# Header and footer for the generated Go source file. The body is generated by
HEADER = """
// Code generated by scripts/generate-template-fixtures.py; DO NOT EDIT.
// Regenerate: make generate-template-fixtures
// Merged-generator JSON fixtures live in template_patch_test.go.
package templates_test

const (
"""

FOOTER = ")\n"


def yq_template_patch(rel: str) -> str:
    """
    Extract the .spec.templatePatch field from the given appset fixture.

    Arg:
        rel: The path to the appset fixture, relative to the repository root.

    Returns:
        string: The value of the .spec.templatePatch field, as a string.
    """

    p = ROOT / rel
    return subprocess.check_output(
        ["yq", ".spec.templatePatch", str(p)],
        text=True,
    )


def main() -> int:
    """Regenerate the embedded templatePatch fixtures."""
    parts = [HEADER]

    for param_name, file_path in APPSETS:
        raw = yq_template_patch(file_path)
        if "`" in raw:
            print(f"backtick in template {file_path}", file=sys.stderr)
            return 1

        parts.append(f"\t{param_name} = `")
        parts.append(raw.rstrip("\n"))
        parts.append("`\n\n")

    parts.append(FOOTER)
    OUT.write_text("".join(parts))
    print(f"wrote {OUT}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
