---
##
## This application set is used to create Applications for each of the
## platform kustomize charts, defined in the ./platform directory.
##
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps-kustomize
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kustomize.patch.appset.tenant: "true"
spec:
  goTemplate: true

  ## Add a strategy permiting us to control the ordering of resources
  ## by using labelling.
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  ## Generate applications from the platform repository
  ## NOTICE: These generators are patched in the kustomize/overlays/release/platform.yaml
  ## file. So if you are making any changes here, please make sure to update the overlay file.
  generators:
    - matrix:
        generators:
          - git:
              repoURL: TENANT_REPO
              revision: TENANT_REPO_REVISION
              files:
                - path: "workloads/applications/**/kustomize.yaml"
            selector:
              matchExpressions:
                - key: kustomize.path
                  operator: Exists
                - key: kustomize.revision
                  operator: Exists
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists

  ## Sync Policy for the ApplicationSet
  syncPolicy:
    # Prevents ApplicationSet controller from modifying Applications. Delete is allowed.
    applicationsSync: create-delete

  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "tenant-kustomize-{{ .path.basenameNormalized }}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd
        app.kubernetes.io/managed-by: tenant
        app.kubernetes.io/instance: tenant
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/type: kustomize
        phase: '{{ default "secondary" .sync.phase }}'

    spec:
      ## The project to use for the application
      project: tenant-apps

      ## The sources to use for the application
      source:
        ## We either use the tenant repository of the kustomize.repository
        repoURL: "{{ default .metadata.annotations.tenant_repository .kustomize.repository }}"
        ## We either use the tenant revision of the kustomize.revision (external revision)
        targetRevision: "{{ default .metadata.annotations.tenant_revision .kustomize.revision }}"
        path: '{{ printf "%s/%s" .path.path .kustomize.path }}'
        kustomize: {}

      ## Destination is the cluster to deploy to
      destination:
        server: https://kubernetes.default.svc
        ## /applications/TYPE/[2]/FILE.yaml
        namespace: "{{ index .path.segments 2 }}"

      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          backoff:
            duration: '{{ default "60s" .sync.backoff_duration }}'
            maxDuration: '{{ default "2m" .sync.backoff_max_duration }}'
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
