---
#
## The purpose of this plugin is to read the platform config (added by tenant) from the
## argocd namespace. This is used throughout the ApplicationSet to template out their
## repository, revision, environment and cluster name values. Ensure everything is
## driven from the source of this truth.
##
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-platform-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-platform-config
    spec:
      version: v1.0
      generate:
        command:
          - sh
          - -c
          - kubectl -n ${NAMESPACE} get configmap ${CONFIGMAP} -o jsonpath='{.data.platform\\.yaml}'
        env:
          - name: NAMESPACE
            value: argocd
          - name: CONFIGMAP
            value: platform-config
      init:
        command: [sh, -c, 'echo -"Initializing"']
        env:
