---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}