{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
