---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-amd64
  labels:
    karpenter.sh/nodepool: default-amd64
    karpenter.sh/nodepool-class: default
  annotations:
    karpenter.sh/nodepool-version: "1.2.1"
    karpenter.sh/nodepool-provider: aws
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "karpenter.sh/architecture"
          operator: In
          values: ["amd64"]
  weight: 100
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
