site_name: Kubernetes Platform
repo_url: https://github.com/gambol99/kubernetes-platform

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/overview.md
      - Bootstrapping: architecture/bootstrapping.md
      - System Applications: architecture/system-applications.md
  - Getting Started:
      - Standalone: getting-started/standalone.md
      - Hub & Spoke: getting-started/central.md
  - Tenant Applications:
      - Tenant Namespace: getting-started/tenant-namespace.md
      - Tenant Applications: getting-started/tenant-applications.md
      - Tenant System: getting-started/tenant-system.md
theme:
  name: material
  palette:
    primary: indigo

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
