---
#
## Configuration for the Cilium service mesh helm chart addons (AWS)
#

## The CNI configuration
cni:
  ## The chaining mode to use for the CNI (aws-cni, cilium-cni)
  chainingMode: aws-cni
  ## The exclusive mode to use for the CNI (true, false)
  exclusive: false
## IP masquerade configuration
enableIPv4Masquerade: false
## The endpoint routes configuration
endpointRoutes:
  ## The enabled flag for the endpoint routes (true, false)
  enabled: true
## The mode to use for the routing (native, tunnel)
routingMode: native
