---
name: Validation

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-charts:
    name: Validate Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/chart-testing-action@v2.7.0
      - run: make validate-helm-charts

  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: make lint-yaml

  validate-helm-addons:
    name: Validate Helm Addons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y yq
      - run: make validate-helm-addons

  validate-scripts:
    name: Validate Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          path: scripts

  validate-kustomize:
    name: Validate Kustomize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
      - run: make validate-kustomize

  validate-docs-spelling:
    name: Validate Docs Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}

  validate-e2e:
    if: github.event_name == 'pull_request'
    name: Validate E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.32.0
      - name: Install Kind
        run: |
          curl -sL https://github.com/kubernetes-sigs/kind/releases/download/v0.27.0/kind-linux-amd64 -o kind
          chmod +x kind
      - name: Provision Cluster
        run: make standalone
      - name: Running E2E
        run: |
          tests/check-suite.sh --cloud kind

  publish-docs:
    if: github.ref == 'refs/heads/main'
    name: Publish Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - validate-charts
      - validate-docs-spelling
      - validate-helm-addons
      - validate-kustomize
      - validate-scripts
      - validate-yaml
      - validate-e2e
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
