---
name: Validation

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.filter.outputs.apps }}
      docs: ${{ steps.filter.outputs.docs }}
      templates: ${{ steps.filter.outputs.templates }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            apps:
              - 'apps/**'
            docs:
              - 'docs/**'
            templates:
              - 'tests/templates/**'

  validate-charts:
    name: Validate Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: helm/chart-testing-action@v2.8.0
      - run: make validate-helm-charts

  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install yamllint
      - run: make lint-yaml

  validate-helm-addons:
    name: Validate Helm Addons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install check-jsonschema
      - run: make validate-helm-addons

  validate-kustomize-addons:
    name: Validate Kustomize Addons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install check-jsonschema
      - run: make validate-kustomize-addons

  validate-scripts:
    name: Validate Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          path: scripts

  validate-templates:
    name: Validate ApplicationSets
    needs: changes
    if: needs.changes.outputs.apps == 'true' || needs.changes.outputs.templates == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"
          cache-dependency-path: tests/templates/go.sum
      - run: make validate-templates

  validate-kustomize:
    name: Validate Kustomize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install check-jsonschema
      - uses: azure/setup-kubectl@v5
      - run: make validate-kustomize

  validate-kyverno:
    name: Validate Kyverno Policies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: v1.13.4
      - run: make validate-kyverno

  validate-schemas:
    name: Validate Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: appvia/kubernetes-platform/.github/actions/validate-schemas@main
        with:
          clusters: |
            release/hub/clusters
            release/hub-aws/clusters
            release/standalone/clusters
            release/standalone-aws/clusters
          workloads: |
            release/hub-aws/workloads
            release/standalone/workloads
            release/standalone-aws/workloads

  validate-docs-spelling:
    name: Validate Docs Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}

  publish-docs:
    name: Publish Docs
    if: needs.changes.outputs.docs == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - changes
      - validate-charts
      - validate-docs-spelling
      - validate-helm-addons
      - validate-kustomize
      - validate-kyverno
      - validate-schemas
      - validate-scripts
      - validate-yaml
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: |
          echo "cache_id=$(date --utc '+%V')" >> "${GITHUB_ENV}"
      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
