---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-argocd
  namespace: argocd
spec:
  project: default
  ## Source in the tenant repository and provision a cluster from the values
  ## defined in the cluster definition. Again we use the platform config plugin
  ## to inject the repository and revision values; ensuring everything is
  ## driven by the source of truth.
  source:
    ## TODO: Needs to be changed to point to private repo
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: argo-cd-7.8.3
    path: charts/argo-cd
    helm:
      releaseName: argocd
      values: |
        ## The global configuration for the argocd server
        global:
          ## Options for the network policy
          networkPolicy:
            ## Enable the creation of the network policy
            create: true
            ## Deny all ingress traffic by default
            defaultDenyIngress: true

        configs:
          ## Set the timeout for the reconciliation to 180 seconds
          timeout.reconciliation: 30s
          ## Specify the admin password for the argocd server
          secret:
            argocdServerAdminPassword: "$2a$10$fDcnV8BQs0kwlCpBnQaGgO8Pm7CLESJEU7DbXit/PIN1jOmlPU6JO"
            argocdServerAdminPasswordMtime: "2025-01-24T19:19:24GMT"

  ## Destination is the cluster to deploy to
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  ## Sync policy for the application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
